### ISSUE TITLE
Issue when running the code

### ISSUE THREAD

**Issue by karliell** [pablovin/FaceChannel#5]
Thanks for the excellent work. I met this issue when running the `python runFromFrames.py`

Could you please tell me how to deal with it? Thanks a lot!

```
Started Frame:/data/emotiontracking/pilot_study/0203_zrd_video1/VID_20210203_215752_synced//000001.png
2021-03-12 13:06:00.009635: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2021-03-12 13:06:00.010117: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 3800095000 Hz
Traceback (most recent call last):
  File "runFromFrames.py", line 103, in <module>
    modelDimensional.classify(face))
  File "/data/emotiontracking/FaceChannel/Utils/modelLoader.py", line 52, in classify
    [image]), batch_size=self.BATCH_SIZE, verbose=0)
  File "/home/y/.local/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1629, in predict
    tmp_batch_outputs = self.predict_function(iterator)
  File "/home/y/.local/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "/home/y/.local/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 895, in _call
    filtered_flat_args, self._concrete_stateful_fn.captured_inputs)  # pylint: disable=protected-access
  File "/home/y/.local/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1919, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/home/y/.local/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 560, in call
    ctx=ctx)
  File "/home/y/.local/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError:  Default MaxPoolingOp only supports NHWC on device type CPU
         [[node model_1/max_pooling2d_1/MaxPool (defined at /data/emotiontracking/FaceChannel/Utils/modelLoader.py:52) ]] [Op:__inference_predict_function_738]

Function call stack:
predict_function

```

**Comment by noorkhan219** [comment]
Try executing the following before running model:
keras.backend.set_image_data_format("channels_first")
